name:                itsoadg
version:             0.1.0.0
github:              "trcummings/itsoadg"
license:             BSD3
author:              "Thomsen Cummings"
maintainer:          "thomsencummings@gmail.com"
copyright:           "2018 Thomsen Cummings"

extra-source-files:
- README.md
- ChangeLog.md

data-files:
- assets/fonts/*.TTF
- assets/sprites/*.json
- assets/sprites/*.png
- assets/sfx/*.wav
- assets/glsl/*.glsl
- assets/gamecontrollerdb.txt

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/itsoadg#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.10.4.0 && < 0.11
- hspec
- hspec-expectations
- sdl2
- sdl2-ttf
- sdl2-image
- sdl2-mixer
- mtl
- transformers
- lens
- attoparsec >= 0.13.2.2
- aeson
- vector
- text
- text-conversions
- containers
- extra
- linear
- filepath
- apecs >= 0.5.0.0
- animate >= 0.6.1
- key-state >= 0.2.0
- OpenGL >= 3.0.2.2
- GLUtil >= 0.10.1
- OpenGLRaw >= 3.3.1.0

library:
  source-dirs: src

executables:
  itsoadg-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    # - -fllvm
    # - -optlo-O3
    dependencies:
    - itsoadg

tests:
  itsoadg-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - itsoadg

default-extensions: &extensions
  - GeneralizedNewtypeDeriving
  - ScopedTypeVariables
  - OverloadedStrings
